---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_grpc }}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      CART_SERVICE_PORT: "{{ ports }}"
      VALKEY_ADDR: "{{ valkey_addr }}"
      REDIS_ADDR: "{{ valkey_addr }}"
      ASPNETCORE_URLS: "{{ aspnetcore_urls }}"
      FLAGD_HOST: "{{ flagd_host }}"
      FLAGD_PORT: "{{ flagd_port }}"
    restart_policy: "{{ restart_policy }}"
    memory: "{{ memory_limit }}"
    state: "{{ state }}"
    ports: "{{ ports }}"
    network_mode: "{{ network_name }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_options_max_size }}"
      max-file: "{{ log_options_max_file }}"
      tag: "{{ service_name }}"