---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_http }}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      VERSION: "{{ demo_version }}"

      FLAGD_HOST: "flagd" #TODO Beautify
      FLAGD_PORT: "8013"
      KAFKA_SERVICE_ADDR: "kafka:9092"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "{{ otlp_metrics_temporality_preference }}"
      PORT: "8080"
      FRONTEND_ADDR: "frontend:8080"
      AD_SERVICE_ADDR: "adservice:9555"
      CART_SERVICE_ADDR: "cartservice:7070"
      CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
      CURRENCY_SERVICE_ADDR: "currencyservice:7001"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      RECOMMENDATION_SERVICE_ADDR: "recommendationservice:9001"
      SHIPPING_SERVICE_ADDR: "shippingservice:50050"
      ENV_PLATFORM: "local"
      PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://localhost:8080/otlp-http/v1/traces"
      WEB_OTEL_SERVICE_NAME: "frontend-web"
      OTEL_COLLECTOR_HOST: "localhost"

    restart_policy: unless-stopped
    memory: "{{ memory_limit }}"
    ports: "{{ ports }}"
    state: started
    network_mode: bridge
    networks:
      - name: opentelemetry-demo
    log_driver: "json-file"
    log_options:
      max-size: "5m"
      max-file: "2"
      tag: "{{ service_name }}"