---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_grpc }}"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "{{ otlp_metrics_temporality_preference }}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      OTEL_LOGS_EXPORTER: "{{ logs_exporter }}"
      CHECKOUT_SERVICE_PORT: "{{ ports }}"
      FLAGD_HOST: "{{ flagd_host }}"
      FLAGD_PORT: "{{ flagd_port }}"
      CART_SERVICE_ADDR: "{{ cartservice_addr }}"
      CURRENCY_SERVICE_ADDR: "{{ currencyservice_addr }}"
      EMAIL_SERVICE_ADDR: "{{ emailservice_addr }}"
      PAYMENT_SERVICE_ADDR: "{{ paymentservice_addr }}"
      PRODUCT_CATALOG_SERVICE_ADDR: "{{ productcatalogservice_addr }}"
      SHIPPING_SERVICE_ADDR: "{{ shippingservice_addr }}"
      KAFKA_SERVICE_ADDR: "{{ kafkaservice_addr }}"

    restart_policy: "{{ restart_policy }}"
    memory: "{{ memory_limit }}"
    state: "{{ state }}"
    ports: "{{ ports }}"
    network_mode: "{{ network_name }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_options_max_size }}"
      max-file: "{{ log_options_max_file }}"
      tag: "{{ service_name }}"