---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      OTEL_COLLECTOR_HOST: "{{ otel_collector_host }}"
      FLAGD_HOST: "{{ flagd_host }}"
      FLAGD_PORT: "{{ flagd_port }}"
      OTEL_COLLECTOR_PORT_GRPC: "{{ otel_collector_port_grpc }}"
      OTEL_COLLECTOR_PORT_HTTP: "{{ otel_collector_port_http }}"
      FRONTEND_HOST: "{{ frontend_host }}"
      FRONTEND_PORT: "{{ frontend_port }}"
      GRAFANA_SERVICE_HOST: "{{ grafana_host }}"
      GRAFANA_SERVICE_PORT: "{{ grafana_port }}"
      IMAGE_PROVIDER_HOST: "{{ imageprovider_host }}"
      IMAGE_PROVIDER_PORT: "{{ imageprovider_port }}"
      JAEGER_SERVICE_HOST: "{{ jaeger_host }}"
      JAEGER_SERVICE_PORT: "{{ jaeger_port }}"
      LOCUST_WEB_HOST: "{{ locust_web_host }}"
      LOCUST_WEB_PORT: "{{ locust_web_port }}"
      ENVOY_PORT: "{{ envoy_port }}"
    restart_policy: "{{ restart_policy }}"
    memory: "{{ memory_limit }}"
    ports: "{{ ports }}"
    state: "{{ state }}"
    network_mode: "{{ network_name }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"