---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  with_dict: "{{ env }}"
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env: "{{ env }}"
    restart_policy: unless-stopped
    memory: "{{ memory_limit }}"
    state: started
    ports: "{{ ports }}"
    network_mode: bridge
    networks:
      - name: opentelemetry-demo
    log_driver: "json-file"
    log_options:
      max-size: "5m"
      max-file: "2"
      tag: "{{ service_name }}"