---
dependencies:
  #- role: cartservice #TODO activate
  #- role: currencyservice
  #- role: emailservice
  #- role: paymentservice
  #- role: productcatalogservice
  #- role: shippingservice
  - role: otelcol
  - role: kafka
  #- role: flagd