service_name: ""
demo_version: ""
image_name: ""
otel_collector_host: "localhost"
otel_collector_port_http: "4317"
otlp_metrics_temporality_preference : "cumulative"
memory_limit: "50M"
ports: "8080:8080"
key: "KAFKA_SERVICE_ADDR"