service_name: "emailservice"
demo_version: "1.10.0"
image_name: "ghcr.io/open-telemetry/demo:1.10.0-emailservice"
ports: "6060:6060"
otel_collector_host: "localhost"
otel_collector_port_http: "4318"
otlp_metrics_temporality_preference : "cumulative"
memory_limit: "100M"

logs_exporter: "otlp"
