---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_grpc }}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      FLAGD_HOST: "{{ flagd_host }}"
      FLAGD_PORT: "{{ flagd_port }}"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "{{ otlp_metrics_temporality_preference }}"
      KAFKA_SERVICE_ADDR: "{{ kafkaservice_addr }}"
      PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "{{ otlp_exporter_traces_endpoint }}"
      PORT: "{{ frontendproxy_port }}"
      LOCUST_HOST: "{{ frontendproxy_addr }}"
      LOCUST_WEB_PORT: "{{ ports }}"
      LOCUST_USERS: "{{ locust_users }}"
      LOCUST_HEADLESS: "{{ locust_headless }}"
      LOCUST_AUTOSTART: "{{ locust_autostart }}"
      LOCUST_BROWSER_TRAFFIC_ENABLED: "{{ locust_browser_traffic_enabled }}"
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "{{ protobuf_python }}"
      LOCUST_WEB_HOST: "{{ locust_web_host }}"

    restart_policy: "{{ restart_policy }}"
    memory: "{{ memory_limit }}"
    ports: "{{ ports }}"
    state: "{{ state }}"
    network_mode: "{{ network_name }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_options_max_size }}"
      max-file: "{{ log_options_max_file }}"
      tag: "{{ service_name }}"