---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}:{{ demo_version }}-{{ service_name }}"
    source: pull

- name: Deploy Service
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_grpc }}"
      OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
      OTEL_SERVICE_NAME: "{{ service_name }}"
      FLAGD_HOST: "flagd" #TODO Beautify
      FLAGD_PORT: "8013"
      KAFKA_SERVICE_ADDR: "kafka:9092"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "{{ otlp_metrics_temporality_preference }}"
      PORT: "8080"
      PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcol:8080/otlp-http/v1/traces"
      LOCUST_WEB_PORT: "8089"
      LOCUST_USERS: "10"
      LOCUST_HOST: "http://frontendproxy:8080"
      LOCUST_HEADLESS: "false"
      LOCUST_AUTOSTART: "true"
      LOCUST_BROWSER_TRAFFIC_ENABLED: "true"
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
      LOCUST_WEB_HOST: "0.0.0.0"

    restart_policy: unless-stopped
    memory: "{{ memory_limit }}"
    ports: "{{ ports }}"
    state: started
    network_mode: opentelemetry-demo
    networks:
      - name: opentelemetry-demo
    log_driver: "json-file"
    log_options:
      max-size: "5m"
      max-file: "2"
      tag: "{{ service_name }}"