---
- name: Deploy OpenTelemetry Demo
  hosts: all
  become: true
  pre_tasks:
    #- name: Ensure Docker is installed
    #  apt:
    #    name: docker.io
    #    state: present
    #  become: true

    - name: Ensure default network is created
      docker_network:
        name: opentelemetry-demo
        driver: bridge

  roles:
    - role: accountingservice
      become: true
    - role: adservice
      become: true
    - role: cartservice
      become: true
    - role: checkoutservice
      become: true
    - role: currencyservice
      become: true
    - role: emailservice
      become: true
    - role: frauddetectionservice
      become: true
    - role: kafka
      become: true
    - role: otelcol
      become: true
    - role: frontend
      become: true
    - role: frontendproxy
      become: true
    - role: imageprovider
      become: true
    - role: loadgenerator
      become: true
      #TODO Add other services here...

  post_tasks:
    - name: Ensure services are started
      community.general.launchd:
        name: "{{ item }}"
        state: started
      loop:
        - accountingservice
        - adservice
        - cartservice
        - checkoutservice
        - emailservice
        - frauddetectionserice
        - frontend
        - frontendproxy
        - imageprovider
        - kafka
        - otelcol
        - loadgenerator
        #TODO Add other services here...

    - name: Ensure services are enabled to start at boot
      community.general.launchd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - accountingservice
        - adservice
        - cartservice
        - checkoutservice
        - emailservice
        - frauddetectionserice
        - frontend
        - frontendproxy
        - imageprovider
        - kafka
        - loadgenerator
        - otelcol
        #TODO Add other services here...