---
- name: Deploy OpenTelemetry Demo
  hosts: all
  become: true
  pre_tasks:
    #- name: Ensure Docker is installed
    #  apt:
    #    name: docker.io
    #    state: present
    #  become: true

    - name: Ensure default network is created
      docker_network:
        name: opentelemetry-demo
        driver: bridge

  roles:
    - role: deploy-docker # TODO model dependencies
      become: true
      vars:
        service_name: "accountingservice"
        demo_version: "1.10.0"
        image_name: "ghcr.io/open-telemetry/demo:1.10.0-accountingservice"
        ports: "8080:8080"
        env:
          KAFKA_SERVICE_ADDR: "http://localhost:9092"
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ otel_collector_host }}:{{ otel_collector_port_http }}"
          OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "{{ otlp_metrics_temporality_preference }}"
          OTEL_RESOURCE_ATTRIBUTES: "service.name={{ service_name }},service.namespace=opentelemetry-demo,service.version={{ demo_version }}"
          OTEL_SERVICE_NAME: "{{ service_name }}"

  post_tasks:
    - name: Ensure services are started
      community.general.launchd:
        name: "{{ item }}"
        state: started
      loop:
        - accountingservice
        #- ad-service
        #- cart-service
        #- checkout-service
        #TODO Add other services here...

    - name: Ensure services are enabled to start at boot
      community.general.launchd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - accountingservice
        #- ad-service
        #- cart-service
        #- checkout-service
        #TODO Add other services here...