---
- name: Deploy OpenTelemetry Demo
  hosts: all
  become: true
  pre_tasks:
    #- name: Ensure Docker is installed
    #  apt:
    #    name: docker.io
    #    state: present
    #  become: true

    - name: Ensure default network is created
      docker_network:
        name: opentelemetry-demo
        driver: bridge

  roles:
    - role: accountingservice
      become: true
    - role: kafka
      become: true
    - role: otelcol
      become: true

  post_tasks:
    - name: Ensure services are started
      community.general.launchd:
        name: "{{ item }}"
        state: started
      loop:
        - accountingservice
        - kafka
        - otelcol
        #- ad-service
        #- cart-service
        #- checkout-service
        #TODO Add other services here...

    - name: Ensure services are enabled to start at boot
      community.general.launchd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - accountingservice
        - kafka
        - otelcol
        #- ad-service
        #- cart-service
        #- checkout-service
        #TODO Add other services here...